### PR TITLE
Make HTTP headers externally configurable

### PR DESCRIPTION
**Pull request by nfedyashev**

### CODE REVIEW

**Comment by nfedyashev** [comment]
@diogob 

Travis CI build failed although it works locally on my machine with this local diff:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 86e1efb..40e1592 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -44,15 +44,16 @@ GEM
     jquery-rails (2.1.3)
       railties (>= 3.1.0, < 5.0)
       thor (~> 0.14)
-    json (1.7.5)
+    json (1.8.3)
     mail (2.4.4)
       i18n (>= 0.4.0)
       mime-types (~> 1.16)
       treetop (~> 1.4.8)
     mime-types (1.25)
     multi_json (1.3.6)
-    pg (0.14.0)
+    pg (0.17.1)
     polyglot (0.3.3)
+    power_assert (0.2.2)
     rack (1.4.1)
     rack-cache (1.2)
       rack (>= 0.4)
@@ -95,6 +96,8 @@ GEM
       hike (~> 1.2)
       rack (~> 1.0)
       tilt (~> 1.1, != 1.3.0)
+    test-unit (3.0.8)
+      power_assert
     thor (0.16.0)
     tilt (1.3.3)
     treetop (1.4.15)
@@ -107,6 +110,11 @@ PLATFORMS

 DEPENDENCIES
   jquery-rails
-  pg
+  json (= 1.8.3)
+  pg (= 0.17.1)
   postgresql_lo_streamer!
   rspec-rails (~> 2.11.0)
+  test-unit
+
+BUNDLED WITH
+   1.10.5
diff --git a/postgresql_lo_streamer.gemspec b/postgresql_lo_streamer.gemspec
index 63fbd24..e254cd7 100644
--- a/postgresql_lo_streamer.gemspec
+++ b/postgresql_lo_streamer.gemspec
@@ -18,5 +18,7 @@ Gem::Specification.new do |s|
   s.add_dependency "rails", ">= 3.2.8"

   s.add_development_dependency "rspec-rails", "~> 2.11.0"
-  s.add_development_dependency "pg"
+  s.add_development_dependency "pg", '= 0.17.1'
+  s.add_development_dependency "json", '= 1.8.3'
+  s.add_development_dependency "test-unit"
 end
```

**Comment by diogob** [comment]
Thanks for the PR 👍 
I'll check why the build is failing later tonight

**Comment by nfedyashev** [comment]
@diogob anything I can help you with?

**Comment by diogob** [comment]
@nfedyashev sorry for the delay, but the gem was quite outdated and I updated the code to build using Rails 4.2, ruby 2.3 and latest Rspec. Would you mind rebasing your pull request against latest master?

**Comment by diogob** [comment]
Also if you could add something to the README about the configuration options that would be great ;)

**Comment by David-Gil** [comment]
I really need this pull request for my app...

**Comment by nfedyashev** [comment]
@diogob done and done

@David-Gil meanwhile you can probably use my fork

**Comment by diogob** [comment]
@nfedyashev thanks again, for the PR! I just merged and released the version `1.0.0` of the gem.

**Comment by diogob** [comment]
@David-Gil ^

**Comment by David-Gil** [comment]
Thank you!
@diogob @nfedyashev

**Pull request merged**
